package fr.isika.cda.entities.common;

public enum AcademicLevel {
    CP, CE1, CE2, CM1, CM2, SIXIEME, CINQUIEME, QUATRIEME, TROISIEME, SECONDE,
    PREMIERE, TERMINALE, CLASSESPREPARATOIRES1, CLASSESPREPARATOIRES2
}
